config/routes.rb
Rails.application.routes.draw do
  get 'favorites/update', to: 'favorites#update'
  get 'favorites/index', to: 'favorites#index', as: 'favorites'
  resources :products
  resources :stores do
    post 'store_reviews', to: 'store_reviews#create'
  end
  get 'store_reviews/new', to: 'store_reviews#new'
  devise_for :users
  root to: 'home#page'
  get '/products/:id/buy', to: 'products#buy', as: 'buy'
  get '/orders/:id/success', to: 'orders#success', as: 'success'
  get '/products/:id/cancel', to: 'products#cancel', as: 'cancel'
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  has_many :products, dependent: :destroy
  has_many :store_reviews, dependent: :destroy 
  has_one_attached :banner, dependent: :destroy
  has_many :orders, dependent: :destroy

  self.per_page = 6

  validates :name, 
            presence: true,
            uniqueness: true,
            length: { maximum: 30 }
  validates :description,
            presence: true,
            length: { maximum: 500 }
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, except: [:new, :index, :create]
  before_action :set_store_owner, except: [:new, :index, :create]
  before_action :authenticate_user!, only: [:new, :create]
  before_action :redirect_if_not_store_owner, only: [:edit, :update, :destroy]
  before_action :redirect_if_user_has_store, only: [:new]

  def index
    # @stores = Store.all
    @stores = Store.paginate(page: params[:page])
  end

  def show
    @store_review = StoreReview.new 
    @store_reviews = @store.store_reviews.paginate(page: params[:page], per_page: 3)
    @store_ratings = @store.store_reviews.select(:rating)
    all_ratings = @store.store_reviews.pluck(:rating)
    @store_average_rating = (all_ratings.sum.to_f / all_ratings.length)
  end

  def new
    @store = Store.new
  end

  def edit
  end

  def create
    @store = Store.new(store_params)
    @store.user_id = current_user.id
    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    #assigns the owner of the current store (based on params)
    def set_store_owner
      @store_owner = @store.user_id
    end

    # stops user from creating more than one store
    def redirect_if_user_has_store
      if @user_owns_a_store
        redirect_to current_user.store, notice: 'Sorry, you already have a store'
      end
    end
    
    def redirect_if_not_store_owner
      # redirect users who dont have a store
      if @user_owns_a_store == false
        redirect_to stores_path, notice: 'Sorry, only the store owner can do this'
      end
      # redirect users who don't own the store
      if user_signed_in? && @store.id != current_user.store.id
        redirect_to stores_path, notice: 'Sorry, only the store owner can do this'
      end
    end

    def store_params
      params.require(:store).permit(:name, :description, :user_id, :banner)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= simple_form_for(@store) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.file_field :banner, accept: 'image/png, image/jpg, image/jpeg' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<h1>Stores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.description %></td>
        <td><%= link_to 'Show', store %></td>
        <% if user_signed_in? && @user_owns_a_store && store.id == current_user.store.id %>
          <td><%= link_to 'Edit', edit_store_path(store) %></td>
          <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create a new store', new_store_path if @user_owns_a_store == false %>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
<h2><%= @store.name %></h2>
<p>
  <%= cl_image_tag(@store.banner.key, cloud_name: 'adriana-developer') if @store.banner.attached? %>
</p>

<p>
  <%= @store.description %>
</p>

<% if @store_average_rating >= 0 %>
  <p>
    <strong>Average rating:</strong>
    <%= @store_average_rating%>/5
    from <%= pluralize(@store.store_reviews.count, "review") %>.
  </p>
<% end %>

<h4>Products:</h4>
<% if @store.products.count == 0 %>
  <p>This store doesn't have any products.</p>
<% else %>
<br>
<div class="card-container">
  <% @store.products.each do |product| %>
      <div class="card" style="width: 18rem;">
        <%= cl_image_tag(product.image.key, crop: :scale, cloud_name: 'adriana-developer', class: "card-img-top") if product.image.attached? %>
        <div class="card-body">
          <h5 class="card-title"><%= product.name %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= product.availability ? "In stock" : "Sold out" %></h6>
          <%= link_to_if product.availability, 'Shop', product %>
          <% if user_signed_in? && @user_owns_a_store && current_user.store.id == @store.id %>
            <%= link_to 'Edit', edit_product_path(product) %>
          <% end %>
        </div>
      </div>
  <% end %>
<% end %>
</div>


<!-- only store owner has these buttons -->
<% if user_signed_in? && @user_owns_a_store && current_user.store.id == @store.id %>
<br>
<div class="store-management-links">
    <button>
      <%= link_to "Add a new product", new_product_path %>
    </button>
  <button>
    <%= link_to 'Edit your store', edit_store_path(@store) %>
  </button>
</div>
<br>
<% end %>

<h5>Reviews:</h5>
<% @store_reviews.each do |review| %>
  <div class="review-card">
    <p>Rating: <%= review.rating %></p>
    <p><%= review.comment %></p>
  </div>
  <br>
  <% end %>
<%= will_paginate @store_reviews %>

<!-- user doesn't own this store -->
<% unless user_signed_in? && @user_owns_a_store && current_user.store.id == @store.id %>
<hr>
  <h5>
    Leave a review:
  </h5>
    <%= simple_form_for [@store, @store_review], local: true do |f| %> 
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <div class="form-inputs">
          <%= f.input :rating,
                      as: :integer, 
                      collection: ["1","2","3","4","5"], 
                      # { class="form-check-input" },
                      # item_wrapper_class: 'inline',
                      as: :radio_buttons, 
                      class: "form-check-label",
                      error: "You must provide a rating" %>
          <%= f.input :comment, 
                    label: "Comments:", 
                    error: "You must provide a comment" %>
        </div>
        <div class="form-actions">
          <%= f.button :submit, "Leave your review" %>
        </div>
    <% end %>
<% end %>