config/routes.rb
Rails.application.routes.draw do
  get 'favorites/update', to: 'favorites#update'
  get 'favorites/index', to: 'favorites#index', as: 'favorites'
  resources :products
  resources :stores do
    post 'store_reviews', to: 'store_reviews#create'
  end
  get 'store_reviews/new', to: 'store_reviews#new'
  devise_for :users
  root to: 'home#page'
  get '/products/:id/buy', to: 'products#buy', as: 'buy'
  get '/orders/:id/success', to: 'orders#success', as: 'success'
  get '/products/:id/cancel', to: 'products#cancel', as: 'cancel'
end

app/views/shared/_navbar.html.erb
<ul class="nav justify-content-end">
    <li class="nav-item">
      <%= link_to "Shop", products_path, class: "nav-link" %>
    </li>

    <% if user_signed_in? %>
        <% if @user_owns_a_store %>
            <li class="nav-item">
                <%= link_to "Manage your store", store_path(current_user.store), class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Create a new product", new_product_path, class: "nav-link" %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to "Create a store", new_store_path, class: "nav-link" %>
            </li>
        <% end %>
    <li class="nav-item">
        <%= link_to "Your favourites", favorites_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
    </li>
    <% else %>
        <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Create account", new_user_registration_path, class: "nav-link" %>
        </li>
    <% end %>
  </ul>