config/routes.rb
Rails.application.routes.draw do
  get 'favorites/update', to: 'favorites#update'
  get 'favorites/index', to: 'favorites#index', as: 'favorites'
  resources :products
  resources :stores do
    post 'store_reviews', to: 'store_reviews#create'
  end
  get 'store_reviews/new', to: 'store_reviews#new'
  devise_for :users
  root to: 'home#page'
  get '/products/:id/buy', to: 'products#buy', as: 'buy'
  get '/orders/:id/success', to: 'orders#success', as: 'success'
  get '/products/:id/cancel', to: 'products#cancel', as: 'cancel'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def page
    @stores = Store.paginate(page: params[:page], per_page: 3)
    @new_products = Product.order("created_at DESC").take(4)
    @plants = Product.find_by_category("Plant")
    @easy_plants = Product.find_by_difficulty("Plant beginner")
    @medium_plants = Product.find_by_difficulty("Mildly smug") 
    @difficult_plants = Product.find_by_difficulty("Full blown #plantfluencer")
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/page.html.erb
<h1>Welcome to Soilmates!</h1>

<!-- sellers -->
<div>
    <h3>Our sellers:</h3>
    <div class="card-container">
        <% @stores.each do |store| %>
            <div class="card" style="width: 18rem;">
              <%= cl_image_tag(store.banner.key, crop: :scale, cloud_name: 'adriana-developer', class: "card-img-top") if store.banner.attached? %>
              <div class="card-body">
                <h5 class="card-title"><%= store.name %></h5>
                <p><%= store.description %></p>
                <%= link_to 'See this store', store %>
              </div>
            </div>
        <% end %>
    </div>
    <button>
        <%= link_to "View all sellers", stores_path %>
    </button>
</div>
<br>

<!-- newest products -->
<div>
    <h3>What's new:</h3>
    <div class="card-container">
        <% @new_products.each do |product| %>
          <% if product.availability == true %>
            <div class="card" style="width: 18rem;">
              <%= cl_image_tag(product.image.key, crop: :scale, cloud_name: 'adriana-developer', class: "card-img-top") if product.image.attached? %>
              <div class="card-body">
                <h5 class="card-title"><%= product.name %></h5>
                <%= link_to 'Shop', product %>
              </div>
            </div>
            <% end %>
        <% end %>
    </div>
    <button>
        <%= link_to "Shop all products", products_path %>
    </button>
</div>
<br>

<!-- -->