config/routes.rb
Rails.application.routes.draw do
  get 'favorites/update', to: 'favorites#update'
  get 'favorites/index', to: 'favorites#index', as: 'favorites'
  resources :products
  resources :stores do
    post 'store_reviews', to: 'store_reviews#create'
  end
  get 'store_reviews/new', to: 'store_reviews#new'
  devise_for :users
  root to: 'home#page'
  get '/products/:id/buy', to: 'products#buy', as: 'buy'
  get '/orders/:id/success', to: 'orders#success', as: 'success'
  get '/products/:id/cancel', to: 'products#cancel', as: 'cancel'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store
  has_one_attached :image, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  self.per_page = 12

  validates :name, 
            presence: true
  validates :description, 
            presence: true,
            length: { maximum: 500 }
  validates :availability, 
            presence: true
  validates :category, 
            presence: true
  validates :price, 
            presence: true, 
            numericality: true,
            numericality: { greater_than: 0.01 }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :buy, :favorite]
  
  # set the store that owns the product
  before_action :set_products_store, only: [:show, :edit, :update, :destroy, :buy, :favorite]

  # user must be signed in for everything except show and index
  before_action :authenticate_user!, except: [:index, :show]

  # redirect if user is not the store manager for the product
  before_action :redirect_non_store_owner, only: [:edit, :udpate, :destroy]

  # make sure user creates a store before creating products
  before_action :check_user_has_store, only: [:new, :create]

  def index
    # @all_products = Product.all
    # @products = @all_products.paginate(page: params[:page])
    # puts "HERE"
    # pp @products
    @products = Product.paginate(page: params[:page])
  end

  def show
    @favorite_exists = Favorite.where(product: @product, user: current_user) == [] ? false : true
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    @product.store_id = current_user.store.id

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def buy      
      Stripe.api_key = ENV['STRIPE_PRIVATEKEY']
      session = Stripe::Checkout::Session.create({
        payment_method_types: ['card'],
        mode: 'payment',
        success_url: success_url(params[:id]), 
        cancel_url: cancel_url(params[:id]),
        # what is being bought
        line_items: [ 
          {
            price_data: {
              currency: 'aud',
              product_data: {
                name: @product.name,
                description: @product.description,
              },
              unit_amount: (@product.price.to_f * 100).to_i  
            },
            quantity: 1
          }
        ]
        })
        
        render json: session
  end
  
  def cancel
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def set_products_store
      store_id_of_product = @product.store_id
      @store_that_owns_product = Store.find(store_id_of_product)
    end

    def redirect_non_store_owner
      if @user_owns_a_store == false 
        # if the current user has no store, redirect them
        redirect_to products_path, notice: 'Sorry, only the store owner can do this'
      end
      if user_signed_in? && @store_that_owns_product.user_id != current_user.id
        # if the current user's store id doesn't match the products store id, redirect
        redirect_to products_path, notice: 'Sorry, only the store owner can do this'
      end
    end

    def check_user_has_store
      # ensure a user creates a store before creating a product
      if @user_owns_a_store == false
        redirect_to new_store_path, notice: 'Please create a store to start selling'
      end
    end

    def product_params
      params.require(:product).permit(:name, :description, :availability, :category, :light, :difficulty, :price, :store_id, :image, :page)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :availability, label: "Available now?" %>
    <%= f.input :category, collection: ["Plant", "Pot", "Plant Care", "Accessories", "Tools"], as: :radio_buttons %>
    <%= f.input :light, collection: ["Low", "Medium", "Bright"], as: :radio_buttons %>
    <%= f.input :difficulty, collection: ["Plant beginner", "Mildly smug", "Full blown #plantfluencer"], as: :radio_buttons %>
    <%= f.input :price %>
    <%= f.file_field :image, accept: 'image/png, image/jpg, image/jpeg' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/cancel.html.erb
<h2>Payment cancelled.</h2>

<p>
    <%= link_to "Continue shopping", products_path %>
</p>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Shop all</h1>
 
<br><br>
<div class="card-container">
  <% @products.each do |product| %>
    <% if product.availability == true %>
      <div class="card" style="width: 18rem;">
        <%= cl_image_tag(product.image.key, crop: :scale, cloud_name: 'adriana-developer', class: "card-img-top") if product.image.attached? %>
        <div class="card-body">
          <h5 class="card-title"><%= product.name %></h5>
          <%= link_to 'Shop', product %>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
    <% will_paginate @products %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <%= cl_image_tag(@product.image.key, crop: :scale, width: 600, cloud_name: 'adriana-developer') if @product.image.attached? %>
</p>

<p>
  <% if user_signed_in? %>
    <button>
      <%= link_to favorite_text, favorites_update_path(product: @product), id: 'favorite_link', remote: true %>
    </button>
  <% end %>
</p>

<h2>
  <%= @product.name %>
</h2>

<p>
  <%= @product.description %>
</p>

<p>
  $<%= @product.price %>
</p>

<p>
  <% if @product.light %>
  This plant requires <%=@product.light.downcase%> light.
  <% end %>
</p>

<p>
  <% if @product.difficulty %>
  Suitable for a "<%=@product.difficulty.downcase%>" caretaker.
  <% end %>
</p>

<p>
  <strong>Available?</strong>
  <%= @product.availability ? "✔️" : "❌" %>
</p>

<!-- if user is signed in and owns the store that owns these products -->
<% if user_signed_in? && @user_owns_a_store && @product.store_id == current_user.store.id %>
  <td><%= link_to 'Edit', edit_product_path(@product) %></td>
  <td><%= link_to 'Destroy', @product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>

<p>
  <strong>From:</strong>
  <%= link_to @product.store.name, store_path(@product.store_id) %>
</p>

<p>
  <% if @product.availability && user_signed_in? %>
    <button id="buy-now-button">Buy Now</button>
  <% elsif user_signed_in? && @user_owns_a_store && @product.store_id == current_user.store.id %>
    <button type="button" disabled>Buy Now</button>
  <% elsif !user_signed_in?  %>
  <p>Please <%= link_to "sign in", new_user_session_path %> to place an order.</p>
    <button type="button" disabled>Buy Now</button>
  <% elsif !@product.availability && user_signed_in? %>
    <p>Product sold out.</p> 
    <button type="button" disabled>Buy Now</button>
  <% end %>
</p>

<script src="https://js.stripe.com/v3/"></script>

<script>
	const stripe = Stripe('<%= ENV["STRIPE_PUBLICKEY"] %>')
	const buyButton = document.getElementById('buy-now-button')

	buyButton.addEventListener('click', function() {
		fetch('<%= buy_path(@product.id) %>', { 
			method: 'GET'
		})
		.then(function(response) {
			return response.json()
		})
		.then(function(session) {
			return stripe.redirectToCheckout({ sessionId: session.id })
		}) 
	})
</script>

app/views/products/success.html.erb
<h2>Payment successful!</h2>

<p>Thanks for shopping with Soilmates!</p>

<p>
    <%= link_to "Continue shopping", products_path %>
</p>

<p>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
</p>